ackermann_controller_bridge:
  ros__parameters:
    command_topic: /ackermann_cmd_joint_states
    steering_command_topic: /steering_position_controller/commands
    wheel_command_topic: /wheel_velocity_controller/commands
    steering_joint_names:
      - f_left_steer
      - f_right_steer
      - b_leftsteer
      - b_rightsteer
    wheel_joint_names:
      - f_leftwheel
      - f_rightwheel
      - b_leftwheel
      - b_rightwheel
    wheel_command_multipliers:
      - 1.0
      - -1.0
      - 1.0
      - -1.0
