ackermann_cmd_node:
  ros__parameters:
    wheelbase: 0.406
    track_width: 0.33112
    wheel_radius: 0.052
    max_steer_angle: 0.8
    cmd_vel_topic: /cmd_vel
    command_topic: /ackermann_cmd_joint_states
    steering_joint_names:
      - f_left_steer
      - f_right_steer
      - b_leftsteer
      - b_rightsteer
    drive_joint_names:
      - f_leftwheel
      - f_rightwheel
      - b_leftwheel
      - b_rightwheel
