ackermann_joint_state_bridge:
  ros__parameters:
    command_topic: /ackermann_cmd_joint_states
    joint_state_topic: /joint_states
    publish_rate_hz: 50.0
    joint_names:
      - f_left_steer
      - f_right_steer
      - b_leftsteer
      - b_rightsteer
      - f_leftwheel
      - f_rightwheel
      - b_leftwheel
      - b_rightwheel
