localization_input_node:
  ros__parameters:
    imu_input_topic: /imu/data
    imu_output_topic: /imu/data/filtered
    imu_frame_id: imu_link
    joint_state_topic: /joint_states
    wheel_odom_topic: /wheel/odom
    drive_joint_names:
      - f_leftwheel
      - b_leftwheel
      - b_rightwheel
      - f_rightwheel
    steer_joint_names:
      - f_left_steer
      - b_leftsteer
      - b_rightsteer
      - f_right_steer
    wheel_positions:
      - 0.2014
      - 0.16556
      - -0.20473
      - 0.16556
      - -0.2046
      - -0.16556
      - 0.20127
      - -0.16556
    effective_wheel_radius: 0.052
    drive_joint_multipliers:
      - 1.0
      - 1.0
      - -1.0
      - -1.0
    odom_frame: odom
    base_frame: base_footprint
    publish_tf: false
